Directory = CS.System.IO.Directory
File = CS.System.IO.File
UIManager=CS.UIManager
Event=CS.DelegetEvent
--UnityEngine

System = CS.System
Time = CS.UnityEngine.Time
deltaTime=Time.deltaTime
Debug = CS.UnityEngine.Debug
GameObject = CS.UnityEngine.GameObject
Vector3 = CS.UnityEngine.Vector3
Vector4 = CS.UnityEngine.Vector4
Quaternion = CS.UnityEngine.Quaternion
Vector2 = CS.UnityEngine.Vector2
Color = CS.UnityEngine.Color
Color32 = CS.UnityEngine.Color32
Instantiate = GameObject.Instantiate
LayerMask = CS.UnityEngine.LayerMask
Resources = CS.UnityEngine.Resources
Transfrom = CS.UnityEngine.Transfrom
Tweening = CS.DG.Tweening
DOTween = CS.DG.Tweening.DOTween
UI = CS.UnityEngine.UI
Input = CS.UnityEngine.Input
KeyCode = CS.UnityEngine.KeyCode
Rect = CS.UnityEngine.Rect
Application = CS.UnityEngine.Application
RuntimePlatform = CS.UnityEngine.RuntimePlatform
Rect = CS.UnityEngine.Rect
Texture2D = CS.UnityEngine.Texture2D
TextureFormat = CS.UnityEngine.TextureFormat
Sprite = CS.UnityEngine.Sprite
Convert = CS.System.Convert
Screen = CS.UnityEngine.Screen
ScreenOrientation = CS.UnityEngine.ScreenOrientation
StavePracticeData = CS.StavePracticeData
ScreenResolution = CS.ScreenResolution
TextAnchor = CS.UnityEngine.TextAnchor
MediaPlayer = CS.RenderHeads.Media.AVProVideo.MediaPlayer
Destroy=CS.UnityEngine.Object.Destroy
