---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mac.
--- DateTime: 2020/7/20 6:40 下午
---
test={}

function test:func()
    print(2222222)
end

function test:func1(a,b)
    print(a+b)
end

return test



